name: certora-basic

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - certora
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    if:
      github.event.pull_request.head.repo.full_name == github.repository || (github.event_name == 'push' &&
      github.ref == format('refs/heads/{0}', github.event.repository.default_branch))
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Munged
        run: |
          cd certora/basic
          touch applyHarness.patch
          make munged

      - uses: Certora/certora-run-action@v1
        with:
          cli-version: 7.29.1
          configurations: |-
            certora/basic/conf/AToken.conf
            certora/basic/conf/ReserveConfiguration.conf
            certora/basic/conf/UserConfiguration.conf
            certora/basic/conf/VariableDebtToken.conf
            certora/basic/conf/NEW-pool-no-summarizations.conf
            certora/basic/conf/stableRemoved.conf
            certora/basic/conf/EModeConfiguration.conf
            certora/basic/conf/RwaAToken.conf
            certora/basic/conf/NEW-pool-simple-properties.conf --rule cannotDepositInInactiveReserve
            certora/basic/conf/NEW-pool-simple-properties.conf --rule cannotDepositInFrozenReserve
            certora/basic/conf/NEW-pool-simple-properties.conf --rule cannotDepositZeroAmount
            certora/basic/conf/NEW-pool-simple-properties.conf --rule cannotWithdrawZeroAmount
            certora/basic/conf/NEW-pool-simple-properties.conf --rule cannotWithdrawFromInactiveReserve
            certora/basic/conf/NEW-pool-simple-properties.conf --rule_sanity none --rule cannotBorrowZeroAmount
            certora/basic/conf/NEW-pool-simple-properties.conf --rule_sanity none --rule cannotBorrowOnInactiveReserve
            certora/basic/conf/NEW-pool-simple-properties.conf --rule_sanity none --rule cannotBorrowOnReserveDisabledForBorrowing
            certora/basic/conf/NEW-pool-simple-properties.conf --rule_sanity none --rule cannotBorrowOnFrozenReserve
          solc-versions: 0.8.19
          comment-fail-only: false
          solc-remove-version-prefix: "0."
          job-name: "Certora Prover Run"
          certora-key: ${{ secrets.CERTORAKEY }}
          install-java: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# Put back the following rule after ticket 8889 is closed
# certora/basic/conf/NEW-pool-no-summarizations.conf ##### waiting for  

