name: certora-solvency

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - certora
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    if:
      github.event.pull_request.head.repo.full_name == github.repository || (github.event_name == 'push' &&
      github.ref == format('refs/heads/{0}', github.event.repository.default_branch))
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Munged
        run: |
          cd certora/solvency
          touch applyHarness.patch
          make munged

      - uses: Certora/certora-run-action@v1
        with:
          cli-version: 7.31.0
          configurations: |-
            certora/solvency/confs/rayMulDiv-CVL-check.conf 
            certora/solvency/confs/aToken-check.conf 
            certora/solvency/confs/variableDebtToken-check.conf 
            certora/solvency/confs/solvency/supply.conf 
            certora/solvency/confs/solvency/withdraw.conf 
            certora/solvency/confs/solvency/borrow.conf 
            certora/solvency/confs/solvency/flashloan.conf 
            certora/solvency/confs/solvency/repay-lemma.conf 
            certora/solvency/confs/solvency/repay-main.conf 
            certora/solvency/confs/solvency/repayWithATokens-lemma.conf 
            certora/solvency/confs/solvency/repayWithATokens-main.conf --rule_sanity "none" 
            certora/solvency/confs/solvency/liquidationCall/lemma-revertsIF_totDbt_of_DBTasset_is0.conf 
            certora/solvency/confs/solvency/liquidationCall/lemma-DBTasset.conf 
            certora/solvency/confs/solvency/liquidationCall/main-DBTasset.conf 
            certora/solvency/confs/solvency/liquidationCall/main-COLasset.conf 
            certora/solvency/confs/solvency/liquidationCall/lemma-COLasset.conf --rule_sanity "none" 
            certora/solvency/confs/solvency/liquidationCall/main-COLasset-totSUP0.conf --rule_sanity "none" 
            certora/solvency/confs/solvency/liquidationCall/lemma-COLasset-totSUP0.conf 
            certora/solvency/confs/solvency/liquidationCall/burnBadDebt-assetINloop.conf 
            certora/solvency/confs/solvency/liquidationCall/burnBadDebt-assetNOTINloop.conf 
            certora/solvency/confs/solvency/liquidationCall/main-SAMEasset.conf 
            certora/solvency/confs/solvency/liquidationCall/lemma-SAMEasset.conf
          solc-versions: 0.8.27
          comment-fail-only: false
          solc-remove-version-prefix: "0."
          job-name: "Certora Prover Run"
          certora-key: ${{ secrets.CERTORAKEY }}
          install-java: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# Put back the following rule after ticket 8889 is closed
# certora/basic/conf/NEW-pool-no-summarizations.conf ##### waiting for

